// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNCNqAJY033u2gVOjCMUp0nZIiTGqyank',
    appId: '1:1058273368169:web:af3dc533cb5f944a846af8',
    messagingSenderId: '1058273368169',
    projectId: 'instagram-clone-aff0f',
    authDomain: 'instagram-clone-aff0f.firebaseapp.com',
    storageBucket: 'instagram-clone-aff0f.appspot.com',
    measurementId: 'G-1NSVSD7DSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHMsZKBSJgeRWpJzv1fjctwZ76shoT3a0',
    appId: '1:1058273368169:android:673fb174c2e6e523846af8',
    messagingSenderId: '1058273368169',
    projectId: 'instagram-clone-aff0f',
    storageBucket: 'instagram-clone-aff0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYJ1ayLGIj5majrfI5gmQv6dAZ63BPwR4',
    appId: '1:1058273368169:ios:58988bab17e2a827846af8',
    messagingSenderId: '1058273368169',
    projectId: 'instagram-clone-aff0f',
    storageBucket: 'instagram-clone-aff0f.appspot.com',
    iosClientId: '1058273368169-6ulda0i5q6vrck6vb6mqugskd7fr7doc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYJ1ayLGIj5majrfI5gmQv6dAZ63BPwR4',
    appId: '1:1058273368169:ios:58988bab17e2a827846af8',
    messagingSenderId: '1058273368169',
    projectId: 'instagram-clone-aff0f',
    storageBucket: 'instagram-clone-aff0f.appspot.com',
    iosClientId: '1058273368169-6ulda0i5q6vrck6vb6mqugskd7fr7doc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
